- src/main/resources/migrations/common/R__v_contact_addresses.sql
- src/main/resources/migrations/common/R__v_contact_identities.sql
- src/main/resources/migrations/common/R__v_contact_phone_numbers.sql
- src/main/resources/migrations/common/R__v_contact_restriction_details.sql
- src/main/resources/migrations/common/R__v_contacts_with_primary_address.sql
- src/main/resources/migrations/common/R__v_prisoner_contact_restriction_details.sql
- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
- src/main/resources/migrations/common/V2025.02.20.18__column_lengths.sql
All the views rely on contact_identity or reference_codes so need to be dropped and recreated.
> PRC-489: Fix migrations

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactEmailFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/email/CreateEmailRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/email/CreateMultipleEmailsRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/email/EmailAddress.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/email/UpdateEmailRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmailController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactEmailFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleEmailsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmailControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactEmailServiceTest.kt
Support for the "add another" pattern in the UI when adding email addresses. Moved email request entities into common package. Will follow suit for other APIs as I come to them.
> PRC-465: Add multiple email address API

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/ContactSearchRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/email/EmailAddress.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/AddContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactWithRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleEmailsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigratePrisonerDomesticStatusIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigratePrisonerNumberOfChildrenIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/ContactSearchRequestTest.kt
Append the path to the element if it's a field error. Did some shenanigans to handle where the field name is added to the start of the message.
> PRC-465: Error message formatting for child elements

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressPhoneFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/CreateMultiplePhoneNumbersRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactAddressPhoneController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmailController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/util/PhoneNumberUtils.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressPhoneFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/util/PhoneNumberTestUtils.kt
Re-uses the request from contact address phone as it's the same and the parent ids are part of the URL.
Also minor swagger fix on other recently added multi add APIs
> PRC-464: Add multiple address phone numbers API

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactNameDetails.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactNameIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
Small API to be used when only the name is required. This avoids loading all phone numbers, addresses, etc.
> PRC-506: Get contact name API

- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
Set connection pool properties to avoid hanging when connection pool is busy (max wait for connection 1 second, max time to validate session 0.5 seconds).
Increase connection pool size to 25 (in line with CSIP).
Attempt to set query timeout to 30 seconds.
Configure slow SQL log, anything slower than 10 seconds will log an info log.
> PRC-531: Set db timeouts

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/exception/DuplicateEmailException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactEmailService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleEmailsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactEmailServiceTest.kt
Unfortunately this can't be enforced with a unique index as NOMIS currently contains duplicates on a contact.
> PRC-465: Check for duplicate email on contact

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactFacadeTest.kt
PRC-535 - API - Allow setting identity documents when creating a new contact
> PRC-535 - API - Allow setting identity documents when creating a new contact

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/client/prisonersearch/PrisonerNumbers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/client/prisonersearch/PrisonerSearchClient.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactLinkedPrisonerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/wiremock/PrisonerSearchApiMockServer.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersServiceTest.kt
Lookup linked prisoners using the batch API rather than one prisoner at a time. This API just omits any prisoners that can't be found from the results.
> PRC-539: Use batch API for linked prisoner lookup

- src/main/resources/application.yml
This is to allow syscon's rec process to go a bit quicker.
> PRC-000: Bump max page size to 300

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
Spring thinks it knows better even though the annotations where telling it it's not required... this forces it to be not required.
> Fix swagger for optional create fields

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/MapSortProperties.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactSearchRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/MapSortPropertiesTest.kt
Made date of birth sort with nulls as if they are the eldest so nulls first/last depending on asc/desc.
Fixed issue where if there are multiple fields being sorted on it was only the last applied.
Removed default sort which was undocumented and might provide unexpected results.
Properly map all fields from API to db type. This is to make things like sorting on id work where the field in the API is called `id` but in the database entity it's called `contactId` so a user would sort on `id` as that's what's in the API but it wouldn't work and failed silently.
> PRC-577: Contact search sort fixes & improvements

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactSearchResultItemPage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/LinkedPrisonerPage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactSummaryPage.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactSummaryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactLinkedPrisonersController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactLinkedPrisonerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactLinkedPrisonersControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactFacadeTest.kt
Changed linked prisoners to page in memory to allow sorting based on name then prisoner number. I've manually tested this with 10000 linked prisoners and it took less than 15 seconds.
Also move to PagedModel instead of PageImpl to fix a spring warning about using an unsafe type. This is a breaking change and needs some fixes to the client code.
Also fixed a number of swagger issues with the paged endpoints.
> PRC-136: Page and sort linked prisoners

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/ContactWithAddressEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactSummaryEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactsServiceMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/MapSortProperties.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/PrisonerContactMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactSearchResultItem.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactSummary.kt
- src/main/resources/migrations/common/R__v_contacts_with_primary_address.sql
- src/main/resources/migrations/common/R__v_prisoner_contacts.sql
- src/main/resources/migrations/test/V2024.08.02.4__example_data.sql
- src/main/resources/migrations/test/V2024.08.02.5__reset_example_sequences.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/SearchContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/LinkedPrisonersServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactRelationshipServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt
For contact search and prisoner contact search to allow showing if the contact is deceased or not in the results tables.
> PRC-549: Add deceased date to search results

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/SentryConfig.kt
There are a large number of events on the sentry due to the daily reconciliation process, which calls domestic status and number of children sync GET endpoints for every active prisoner and sends entity not found exception error log into the sentry. This is using the sentry quota significantly, So the aim is to reduce this noise reported to the sentry,
> PRC-546 : reduce noise on sentry related to entity not found errors caused as part of reconciliation of new prisoners.

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/SyncContactReconcile.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactAddressRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactIdentityRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactPhoneRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/ContactRestrictionRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactReconciliationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncReconcileIntegrationTest.kt
- src/test/resources/reconcile.tests/cleanup-reconcile-test.sql
- src/test/resources/reconcile.tests/data-for-reconcile-test.sql
Syscon had an issue with the length of time it was taking to reconcile data from a single contact's perspective - 5 hours or so for a reconciliation to run, and issues in time-outs/retries when other services were involved.
This was because they were calling the 3 of the API endpoints meant for the UI and other consumers - which included lookups for reference data, prisoner details, organisation names/descriptions and gathering full data for each.
This endpoint goes straight to the data - no other external calls or lookups - and provides the minimal (but core) data which Andy needs to check that NOMIS and our DB are in line.
> PRC-582: speedy contact reconciliation

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactRelationshipCountEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactRelationshipCount.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactRelationshipCountRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
- src/main/resources/migrations/common/R__v_prisoner_contact_count.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactRelationshipCountIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt
New view to count prisoner contacts by active and inactive status for their current term with an API to match. This is for DPS connects new widget to link into contacts.
Tested the view in dev and it's very fast. It does not bother to verify that the prisoner exists and returns 0 by default.
> PRC-614: Relationship count API

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerContactRelationshipCountEntity.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerContactRelationshipCount.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
- src/main/resources/migrations/common/R__v_prisoner_contact_count.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactRelationshipCountIntegrationTest.kt
What was actually required was not active/inactive but split on social/official. To keep the view fast I've just removed the active/inactive rather than including lots of metrics no-one cares about.
> PRC-614: Change relationship count API to relationship type

- README.md
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactIdentityFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/identity/CreateIdentityRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/identity/CreateMultipleIdentitiesRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/identity/UpdateIdentityRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactIdentityController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactIdentityFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/NotFoundTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactIdentityControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactIdentityServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/util/StubUser.kt
Use the user from the token instead of created/updated by fields. Specify the user on events related to identity docs. Some minor tidy up and docs as requested in previous PR.
> PRC-651: Convert identities to use user

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerNumberOfChildrenFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateOrUpdatePrisonerNumberOfChildrenRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerNumberOfChildrenController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerNumberOfChildrenService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerNumberOfChildrenFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateOrUpdatePrisonerNumberOfChildrenIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerNumberOfChildrenIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/PrisonerMergeControllerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerNumberOfChildrenIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerNumberOfChildrenControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerNumberOfChildrenServiceTest.kt
Use the user from the token instead of created/updated by fields. Specify the user on events related to number of children
> PRC-651: Convert number of children to use user

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/mapping/ContactAddressDetailsMappers.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/CreateContactAddressRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/PatchContactAddressRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/UpdateContactAddressRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactAddressController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsServiceTest.kt
Use username from the token rather than created/updated by.  Also add username to events.
> PRC-651: Use username from token for addresses

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/EmploymentFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/CreateEmploymentRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/PatchEmploymentsRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/UpdateEmploymentRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmploymentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/EmploymentService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/EmploymentFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchEmploymentsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/EmploymentServiceTest.kt
Use username from the token rather than created/updated by.  Also add username to events.
> PRC-651: Use username from token for employments

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerDomesticStatusFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateOrUpdatePrisonerDomesticStatusRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerDomesticStatusController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerDomesticStatusFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateOrUpdatePrisonerDomesticStatusIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerDomesticStatusIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/PrisonerMergeControllerIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerDomesticStatusIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerDomesticStatusControllerTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusServiceTest.kt
Use username from the token rather than requested by.  Also add username to events.
> PRC-651: Use username from token for domestic status

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerDomesticStatusSyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerMergeFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerNumberOfChildrenSyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerDomesticStatusSyncFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerMergeFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerNumberOfChildrenSyncFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsServiceTest.kt
Move username to common property of AdditionalInformation and remove the default user from the outbound event service. Specify system user directly for migrate & sync events.
> PRC-651: Ensure user set on all events

- Dockerfile
Switch to using JDK instead of JRE. This will make the tools available in case we need a thread dump at the cost of a slightly bigger image.
> Switch to JDK

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerContactSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/DuplicateRelationshipException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/AddContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
Reject duplicate relationships (same prisoner number, contact id and relationship to prisoner code) when a new relationship is created by sync or DPS API. Also reject duplicate relationships when updating a contact relationship but only if the user is changing the relationship. Do not reject sync updates to relationships.
This allows existing duplicates in NOMIS to be updated but blocks the creation of new duplicates, we trust NOMIS not to create any more new duplicates as it is validated in the NOMIS UI now.
> PRC-725 & PRC-696: Reject duplicate relationships

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactSummaryRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetAllSummariesForPrisonerAndContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt
This API is to enable showing duplicate relationships and for otherwise dissuading users from creating multiple relationships between a prisoner and contact.
> PRC-704: API to get all summaries for prisoner and contact

- src/main/resources/migrations/common/V2025.05.12.33__update_official_relationships_and_phone_types.sql
As requested by Connect DPS. Also added two missing OFFICIAL_RELATIONSHIPs in case they are added in NOMIS. They are enabled in NOMIS but we decided to leave them disabled in DPS as they are currently unused even in NOMIS.
> PRC-586: Further reference data updates

- src/main/resources/application.yml
Rec is currently failing due to a prisoner with 300 linked contacts.
> Increase max page size for rec

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactEmailIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIdentityIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactPhoneIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactRestrictionIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncEmploymentIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactRestrictionIntegrationTest.kt
Where possible set the username for events based on created by or updated by fields in the request. This is unknown for delete events and also admin functions such as merge and reset where the user remains as SYS.
> PRC-747: Set username on NOMIS source events

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/UserRequestContextConfiguration.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/UserRequestContextConfigurationTest.kt
We should be using the username and not token name and also only be calling it on modifying methods. Added missing tests.
> PRC-764: Fix calling manage users on GET

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerContactsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerServiceTest.kt
For contact list only check the prisoner exists if we get no results, this prevents unnecessary calls to prisoner service.
> PRC-767: Only check prisoner exists if no results

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/Address.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/CreateContactAddressRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/PatchContactAddressRequest.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/address/UpdateContactAddressRequest.kt
- src/main/resources/migrations/common/V2025.08.04.38__increase_property_length.sql
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchContactAddressIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressIntegrationTest.kt
NOMIS has recently updated the property field size to 130 characters and Syscon has detected its causing DLQs , This is to increase the size of the field to 130 chars
> PRC-881 : increase property field size

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/ContactSyncController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactReconciliationService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncReconcileIntegrationTest.kt
- src/test/resources/reconcile.tests/data-for-reconcile-test.sql
Reconciliation - extend to non-current term relationships
AC: introduce a new flag currentTermOnly, with a default of true, When passing currentTermOnly false, then all contacts with both current and non-current relationships should be returned
> PRC-882 : Reconciliation - extend to non current term relationships

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerContactService.kt
Test evidence: update approvalStatus from both NOMIS and DPS logs if the value has been changed with the user name and current value and new value
Update from NOMIS:
Update from DPS:
> PRC-901 : Add a metric to see how often approval is toggled by NOMIS vs DPS

- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/internal/DeletedResponse.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactRelationshipIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactFacadeTest.kt
Update the existing logic to 
We delete a relationship
We should then check - are they in any other relationships? If no, leave the DOB alone.
If yes, are ALL of those relationships internal staff types? If no, leave the DOB alone.
If yes, remove the DOB and send the extra event.
> PRC-903 : Send CONTACT_UPDATED event to NOMIS when last internal relationships is deleted
