ministryofjustice/hmpps-personal-relationships-api

src/test/resources/application-test.yml

PRC-445 : configuration changes to fix build error

PRC-445 : configuration changes to rename contacts api project name to personal-relationship

---

helm_deploy/hmpps-personal-relationships-api/values.yaml

PRC-445 : configuration changes fix build error

PRC-445 : configuration changes fix build error

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/ContactDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactByIdIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt

merging latest changes of the contact project to personal relationships project

merging latest changes of the contacts project to personal relationships project 

---

src/main/resources/application-local.yml
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/OrganisationServiceTest.kt

Set local to use dev instead of preprod org API.
Add missing tests after refactor.

PRC-481: Small fixes related to org PR

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncUpdatePrisonerNumberOfChildrenRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/SyncPrisonerDomesticStatusResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/sync/SyncPrisonerNumberOfChildrenResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/migrate/MigratePrisonerNumberOfChildrenController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerDomesticStatusSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerNumberOfChildrenSyncController.kt

PRC-426 - update swagger for sync , migration for number of children and domestic status

PRC-426 - update swagger for sync , migration for number of children and domestic status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/entity/PrisonerDomesticStatus.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/migrate/PrisonerDomesticStatusMigrationResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerDomesticStatusRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerDomesticStatusMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerDomesticStatusService.kt
src/main/resources/migrations/common/V2025.02.13.18__prisoner_domestic_status.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerDomesticStatusMigrationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerDomesticStatusServiceTest.kt

PRC-426-create entity service layers for sync , migration for domestic status

PRC-426-create entity service layers for sync , migration for domestic status

---

src/main/resources/migrations/common/V2025.02.24.19__gender_ref_data_update.sql

"Not known / Not recorded" becomes just "Not known" and moves to the bottom of the list. "Not specified" is now 3rd in the list.

PRC-265: Update gender options

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/MigratePrisonerDomesticStatusRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncUpdatePrisonerDomesticStatusRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerDomesticStatusService.kt
src/main/resources/migrations/common/V2025.02.26.24__make_column_nullable.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigratePrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerDomesticStatusIntegrationTest.kt

PRC-426 - fix column size and make nullable

PRC-426 - fix column size and make nullable

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactAddressPhoneFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/CreateContactAddressPhoneRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/CreateMultipleContactPhoneNumbersRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/CreatePhoneRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/PhoneNumber.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/UpdateContactAddressPhoneRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/phone/UpdatePhoneRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactAddressPhoneController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactPhoneFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateMultipleContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactAddressPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactPhoneControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactAddressPhoneServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactPhoneServiceTest.kt

Plus moved all the phone number request objects into their own package

PRC-464: Add multiple contact phone numbers API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/MigratePrisonerDomesticStatusRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/migrate/MigratePrisonerNumberOfChildrenRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/sync/SyncUpdatePrisonerNumberOfChildrenRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerDomesticStatusMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerNumberOfChildrenService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigratePrisonerNumberOfChildrenIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerNumberOfChildrenIntegrationTest.kt

PRC-426 - remove min validation, add max validation for noc 50

PRC-426 - remove min validation, add max validation for noc 50

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerDomesticStatusFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateOrUpdatePrisonerDomesticStatusRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerDomesticStatusResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerDomesticStatusController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerDomesticStatusFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateOrUpdatePrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerDomesticStatusControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusServiceTest.kt

PRC-487 - get and create or update api for domestic status

PRC-487 - get and create or update api for domestic status

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerDomesticStatusFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerNumberOfChildrenFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateOrUpdatePrisonerNumberOfChildrenRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/PrisonerNumberOfChildrenResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerNumberOfChildrenController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerNumberOfChildrenService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerDomesticStatusFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/PrisonerNumberOfChildrenFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerDomesticStatusSyncFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateOrUpdatePrisonerNumberOfChildrenIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetPrisonerNumberOfChildrenIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerNumberOfChildrenControllerTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerNumberOfChildrenServiceTest.kt

PRC-488 - api endpoints for GET and CREATE or UPDATE number of children
also removed the UPDATED domain event as NOMIS is not listening to that,

PRC-488 - api endpoints for get and create or update number of children

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerDomesticStatusController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerNumberOfChildrenController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/migrate/MigratePrisonerDomesticStatusController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerDomesticStatusSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerNumberOfChildrenSyncController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerDomesticStatusService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerNumberOfChildrenService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerNumberOfChildrenServiceTest.kt

PRC-533 : fix swagger docs

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/EmploymentFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/CreateContactRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/CreateEmploymentRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/Employment.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/PatchEmploymentsRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/PatchEmploymentsUpdateEmployment.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/request/employment/UpdateEmploymentRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/ContactEmploymentController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/EmploymentService.kt
src/main/resources/migrations/common/V2025.03.17.26__add_missing_employment_constraint.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/EmploymentFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreateEmploymentIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteEmploymentIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/GetEmploymentIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/PatchEmploymentsIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/UpdateEmploymentIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/EmploymentServiceTest.kt

Also re-added constraint on contact id in employment table.

PRC-565: Create employments with new contact

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerDomesticStatusRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerNumberOfChildrenRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerDomesticStatusMigrationService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerNumberOfChildrenMigrationService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigratePrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigratePrisonerNumberOfChildrenIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerDomesticStatusMigrationServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/migrate/PrisonerNumberOfChildrenMigrationServiceTest.kt

PRC-533 : overwrite existing records during migration

PRC-533 : overwrite existing records during migration

---

build.gradle.kts
helm_deploy/hmpps-personal-relationships-api/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/SentryConfig.kt
src/main/resources/application.yml

PRC-546 :Configure Sentry
Test evidence:
secrets have been created in pre-prod and prod environments
Alert appears in the Slack channel

PRC-546 :Configure Sentry

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerMergeFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerDomesticStatusRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerNumberOfChildrenRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/sync/PrisonerMergeController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerNumberOfChildrenService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/PrisonerMergeService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerDomesticStatusService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerNumberOfChildrenService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/sync/PrisonerMergeFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/PrisonerMergeControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerNumberOfChildrenIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerDomesticStatusServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/PrisonerNumberOfChildrenServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/PrisonerMergeServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerDomesticStatusServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerNumberOfChildrenServiceTest.kt

PRC-576 :handle prisoner merge events from NOMIS

PRC-576 :handle prisoner merge events from NOMIS

---

helm_deploy/values-prod.yaml

PRC-572 : Preprod DB restore from Production

PRC-572 : Preprod DB restore from Production

---

helm_deploy/hmpps-personal-relationships-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/SentryConfig.kt
src/main/resources/application.yml

Update Sentry sampling rate for these requests identified in Sentry with a high number of events.

PRC-588 : update sentry sampling rate

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/client/manage/users/UserDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/User.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/UserRequestContextConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEvents.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/SyncFacadeTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/helpers/Examples.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/migrate/MigrateContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/PrisonerMergeControllerIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncAdminIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactAddressIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactEmailIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIdentityIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactPhoneIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncContactRestrictionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncEmploymentIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerContactRestrictionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerDomesticStatusIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/sync/SyncPrisonerNumberOfChildrenIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/wiremock/ManageUsersApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/events/OutboundEventsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/util/StubUser.kt

Where it's possible on create or update requests.

PRC-749: Add active caseload id to telemetry from NOMIS

---

src/main/resources/application.yml

Rotate connections after 10 minutes.

PRC-763: Set connection max lifetime

---

helm_deploy/hmpps-personal-relationships-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/exception/DuplicatePersonException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/exception/DuplicateRelationshipException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncPrisonerContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/sync/SyncContactServiceTest.kt

Moved them into the common exception package as well

Suppress business exceptions from sentry

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt

We were returning SQL sometimes in the event of an unhandled exception which was flagged by AppSec. Suppress this and return with a reference which can be used to find the error in the logs.

PRC-762: Sanitise errors

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/CacheConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ManageUsersService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/CreatePrisonerContactRestrictionIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ManageUsersServiceIntegrationTest.kt

User details can be cached for up to 12 hours.

PRC-767: Manage users cache

---

helm_deploy/hmpps-personal-relationships-api/values.yaml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HmppsContactsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/exception/RelationshipCannotBeRemovedDueToDependencyException.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/internal/DeletedRelationshipIds.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/PrisonerContactController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/helper/TestAPIClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/resource/DeleteContactRelationshipIntegrationTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/patch/ContactFacadeTest.kt

API to delete relationships. Only allowed when there are no restrictions on a relationship.

PRC-770: API to delete relationships

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/config/HikariPoolLogger.kt
src/main/resources/application.yml

PRC-899-trigger-alert-for-idel-db-connections

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/facade/ContactFacade.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/model/response/RelationshipsApprovedResponse.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/repository/PrisonerContactRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/resource/UtilityController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/service/ContactService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppscontactsapi/integration/ResourceSecurityTest.kt

Support use only.
Ingress restricted to local use only.

PRC-947: Utility endpoint (secured, not public) to approve certain contact relationships to visit.
